apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: builder-rs
  annotations:
    federation.kubernetes.io/replica-set-preferences: |
      {
          "rebalance": true,
          "clusters": {
              "local-7": {
                  "minReplicas": 0,
                  "maxReplicas": 10,
                  "weight": 1
              },
              "gke-cluster-1": {
                  "minReplicas": 0,
                  "maxReplicas": 10,
                  "weight": 1
              }
          }
      }
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 0
  template:
    metadata:
      labels:
        app: builder
    spec:
      containers:
      - name: builder
        image: platform9systems/s2n-builder
