apiVersion: v1
kind: Service
metadata:
  name: ridic-simple-mq
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: TO_BE_FILLED
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
spec:
  ports:
  - port: 443
    targetPort: 8889
    protocol: TCP
  selector:
    app: ridic-simple-mq
  type: LoadBalancer

